### ISSUE TITLE
Migrations are failing 

### ISSUE THREAD

**Issue by MagdaN** [okfde/django-filingcabinet#11]
Applying filingcabinet.0003_auto_20180810_1559…

ValueError: Cannot alter field filingcabinet.DocumentCollection.documents into filingcabinet.DocumentCollection.documents - they are not compatible types (you cannot alter to or from M2M fields, or add or remove through= on M2M fields)

**Comment by stefanw** [comment]
Weird, it once worked, but apparently a long time ago in Django 1.11.
